  
"""Constants for USR-R16 component."""

DOMAIN = "usr_r16"

DEFAULT_NAME = "USR-R16"
DEFAULT_PORT = 8899
DEFAULT_RECONNECT_INTERVAL = 10
DEFAULT_KEEP_ALIVE_INTERVAL = 3
CONNECTION_TIMEOUT = 10
DEFAULT_PASSWORD = 'admin'

